name: Pipeline

on: [push]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sh deploy/script.sh
        env:
          POTATO: 1234
      - run: |
          echo \
          good \
          things \
          happen \
          on \
          new \
          lines
